openapi: 3.0.0
info:
  title: DMS Backend service REST API
  version: '1.0'
  description: |
    REST API for the authentication service.

    This is part of the mandatory exercise.

    Diseño y Mantenimiento del Software. Grado en Ingeniería Informática, Universidad de Burgos, 2021-2022.
  contact:
    name: Universidad de Burgos
tags:
  - name: session
    description: Session-related operations (e.g., login)
  - name: users
    description: User-related operations (e.g., list, create, search)
  - name: roles
    description: Role-related operations (e.g., grant, revoke)
  - name: server
    description: Operations about the server itself (e.g., server status querying)
servers:
  - url: /api/v1
paths:
  '/':
    head:
      summary: Health test for the service
      operationId: dms2122backend.presentation.rest.server.health_test
      responses:
        '204':
          description: Success response (will not redirect)
          content:
            'text/plain':
              schema:
                type: string
      tags:
        - server
  /test:
    get:
      summary: Authenticates a user
      operationId: dms2122backend.presentation.rest.test.test
      responses:
        '200':
          description: A test message
          content:
            'text/plain':
              schema:
                type: string

components:
  schemas:
    UserFullModel:
      type: object
      properties:
        username:
          type: string
      required:
        - username
    UserFullPasswordModel:
      allOf:
        - $ref: '#/components/schemas/UserFullModel'
        - type: object
          properties:
            password:
              type: string
          required:
            - password
    UsersFullListModel:
      type: array
      items:
        $ref: '#/components/schemas/UserFullModel'
  securitySchemes:
    user_credentials:
      type: http
      scheme: basic
      x-basicInfoFunc: dms2122auth.presentation.rest.security.verify_credentials
    user_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: dms2122auth.presentation.rest.security.verify_token
    api_key:
      type: apiKey
      name: X-ApiKey-Auth
      in: header
      x-apikeyInfoFunc: dms2122auth.presentation.rest.security.verify_api_key
